# Generated by Django 3.2.12 on 2022-06-16 16:50

import Product_API.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Description', models.JSONField(default=list)),
                ('Author', models.CharField(default='', max_length=200)),
                ('ProductName', models.CharField(default='', max_length=30)),
                ('ShippingLocation', models.CharField(default='', max_length=50)),
                ('SubItem', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=300)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Product_API.models.Product_Image_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_API.product')),
            ],
        ),
    ]
