# Generated by Django 3.2.12 on 2022-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
