# Generated by Django 3.2.12 on 2022-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
