# Generated by Django 3.2.12 on 2022-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0005_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='EnoughStock',
            field=models.CharField(default='Enough', max_length=10),
        ),
    ]
