# Generated by Django 3.2.12 on 2022-06-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0006_product_enoughstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='EnoughStock',
            new_name='Stock',
        ),
    ]
