# Generated by Django 3.2.12 on 2022-06-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product_API', '0007_rename_enoughstock_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
