# Generated by Django 3.2.12 on 2022-06-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0008_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Author',
        ),
    ]
