# Generated by Django 3.2.12 on 2022-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0009_remove_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Sell', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Properties', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='InvalidSubItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubItem',
        ),
        migrations.AddField(
            model_name='product',
            name='InvalidSubItem',
            field=models.ManyToManyField(related_name='Invalid_SubItem', to='Product_API.ProductSubItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='SubItem',
            field=models.ManyToManyField(related_name='SubItem', to='Product_API.ProductSubItem'),
        ),
    ]
