# Generated by Django 3.2.12 on 2022-08-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0013_productcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
