# Generated by Django 3.2.12 on 2022-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0015_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='SubItemName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
