# Generated by Django 3.2.12 on 2022-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0017_alter_productcomment_subitemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Comment',
            field=models.ManyToManyField(to='Product_API.ProductComment'),
        ),
    ]
