# Generated by Django 3.2.12 on 2022-08-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0018_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
