# Generated by Django 4.0.7 on 2022-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0021_auto_20220825_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SubItem',
            field=models.ManyToManyField(related_name='SubItem', to='Product_API.productsubitem'),
        ),
    ]
