# Generated by Django 4.1 on 2022-10-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0023_alter_product_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.CharField(choices=[('E', 'Enough'), ('S', 'SellOut'), ('s', 'Small')], default='E', max_length=1),
        ),
    ]
