# Generated by Django 4.1.5 on 2023-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0025_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='VideoList',
            field=models.JSONField(default=list),
        ),
    ]
