# Generated by Django 4.2.3 on 2023-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0027_rename_videolist_product_descriptionvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductStauts',
            field=models.BooleanField(default=True),
        ),
    ]
