# Generated by Django 4.2.3 on 2023-11-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0028_product_productstauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductStauts',
            new_name='ProductStatus',
        ),
    ]
