# Generated by Django 4.2.3 on 2023-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0030_product_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Categories',
        ),
    ]
