# Generated by Django 3.2.12 on 2022-07-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserA', to=settings.AUTH_USER_MODEL)),
                ('User_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
