# Generated by Django 3.2.12 on 2022-07-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedata',
            name='User_A',
        ),
        migrations.RemoveField(
            model_name='messagedata',
            name='User_B',
        ),
        migrations.CreateModel(
            name='Chat_Channel_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record', models.ManyToManyField(blank=True, to='Chat_API.MessageData')),
                ('User_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserA', to=settings.AUTH_USER_MODEL)),
                ('User_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
