# Generated by Django 3.2.12 on 2022-07-06 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_API', '0007_auto_20220706_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_channel_record',
            name='User',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
