# Generated by Django 3.2.12 on 2022-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_API', '0008_alter_chat_channel_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
