# Generated by Django 3.2.12 on 2022-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_API', '0009_messagedata_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='Type',
            field=models.CharField(default='String', max_length=10),
        ),
    ]
