# Generated by Django 3.2.12 on 2022-07-10 17:35

import Chat_API.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_API', '0010_messagedata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ImageField(upload_to=Chat_API.models.file_directory_path)),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat_API.messagedata')),
            ],
        ),
    ]
