# Generated by Django 4.1 on 2022-09-27 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_API', '0011_chatmessagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedata',
            name='SenderName',
        ),
        migrations.AddField(
            model_name='messagedata',
            name='Sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
