# Generated by Django 4.1 on 2022-09-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_API', '0013_alter_messagedata_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_channel_record',
            name='ChatName',
        ),
    ]
