# Generated by Django 3.2.12 on 2022-07-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0002_client_websocketkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='WebSocketKey',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
