# Generated by Django 3.2.12 on 2022-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0003_alter_client_websocketkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_subscriber',
        ),
        migrations.AddField(
            model_name='client',
            name='SubScribe_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='SubScribe_End',
            field=models.DateTimeField(null=True),
        ),
    ]
