# Generated by Django 3.2.12 on 2022-07-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0007_alter_businesssubscribe_subscribe_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssubscribe',
            old_name='SubScribe_Date',
            new_name='Subscribe_Date',
        ),
        migrations.RenameField(
            model_name='businesssubscribe',
            old_name='SubScribe_End',
            new_name='Subscribe_End',
        ),
    ]
