# Generated by Django 3.2.12 on 2022-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0008_auto_20220729_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscribe',
            name='Subscribe_Plan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
