# Generated by Django 3.2.12 on 2022-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0009_businesssubscribe_subscribe_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubscribe',
            name='Subscribe_Plan',
            field=models.CharField(max_length=30),
        ),
    ]
