# Generated by Django 3.2.12 on 2022-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0011_client_profileicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_OAuth',
            field=models.BooleanField(default=False),
        ),
    ]
