# Generated by Django 3.2.12 on 2022-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0012_client_is_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_OAuth',
            field=models.BooleanField(),
        ),
    ]
