# Generated by Django 4.1 on 2022-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0016_shoppingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ShoppingAddress',
            field=models.ManyToManyField(to='User_Manager_API.shoppingaddress'),
        ),
    ]
