# Generated by Django 4.1 on 2022-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0018_shoppingaddress_receivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingaddress',
            name='ReceiverName',
            field=models.CharField(max_length=50),
        ),
    ]
