# Generated by Django 4.1 on 2022-10-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0019_alter_shoppingaddress_receivername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='WebSocketKey',
        ),
    ]
