# Generated by Django 4.1 on 2023-01-05 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0020_remove_client_websocketkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Ads_Token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
