# Generated by Django 4.2.3 on 2023-07-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0021_client_ads_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Agreement', models.BooleanField(default=True)),
                ('ConsentGlobalAds', models.BooleanField(default=True)),
                ('ConsentPersonalAds', models.BooleanField(default=True)),
                ('ConsentThirdPartyAds', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Ads_Token',
        ),
        migrations.AddField(
            model_name='client',
            name='Ads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User_Manager_API.advertisement'),
        ),
    ]
