# Generated by Django 4.2.3 on 2023-12-29 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_API', '0031_delete_product_categories'),
        ('User_Manager_API', '0022_advertisement_remove_client_ads_token_client_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=300)),
                ('Product', models.ManyToManyField(blank=True, related_name='Product', to='Product_API.product')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
