# Generated by Django 4.2.3 on 2023-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manager_API', '0023_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_categories',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
