# Generated by Django 4.1 on 2023-01-05 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_API', '0025_alter_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ProductTitle', models.CharField(max_length=100)),
                ('OrderImage', models.ImageField(upload_to='')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_API.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('PaymentMethod', models.CharField(max_length=20)),
                ('DeliveryMethod', models.CharField(max_length=20)),
                ('TransportCode', models.CharField(max_length=200, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Status', models.CharField(default='normal', max_length=20)),
                ('Buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Buyer', to=settings.AUTH_USER_MODEL)),
                ('OrderList', models.ManyToManyField(blank=True, to='Order_API.orderitem')),
                ('Seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Count', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSnapShot',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Description', models.JSONField(default=list)),
                ('ProductName', models.CharField(default='', max_length=30)),
                ('ShippingLocation', models.CharField(default='', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('OrderItemRecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order_API.orderitem')),
                ('Seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnTransportCode', models.CharField(max_length=100, null=True)),
                ('ErrorReason', models.CharField(default='', max_length=200)),
                ('ReturnStatus', models.CharField(default='normal', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('Buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Buyer', to=settings.AUTH_USER_MODEL)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_API.orderitem')),
                ('Seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Seller', to=settings.AUTH_USER_MODEL)),
                ('SubItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_API.ordersubitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSnapShot_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order_API.productsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSnapShot_Description_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order_API.productsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentTitle', models.CharField(max_length=200)),
                ('CommentContent', models.CharField(max_length=1000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField()),
                ('CommentProductName', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_API.product')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Stripe_ID', models.CharField(max_length=200)),
                ('payment_intent', models.CharField(max_length=200)),
                ('PaymentStatus', models.CharField(default='unpaid', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Order', models.ManyToManyField(blank=True, to='Order_API.orderrecord')),
            ],
        ),
        migrations.AddField(
            model_name='ordersubitem',
            name='Comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_API.productcomment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='SubItem',
            field=models.ManyToManyField(blank=True, to='Order_API.ordersubitem'),
        ),
    ]
